mod analytics;
mod bulk_upload;
mod calendar;
mod dashboard;
mod forgot_password;
mod guest_details;
mod guests;
mod hotel_profile;
mod login;
mod messages;
mod not_found;
mod payments;
mod rates;
mod reservations;
mod reviews;
mod room_details;
mod rooms;
mod settings;
mod signup;
mod staff;

pub use analytics::AnalyticsPage;
pub use bulk_upload::BulkUploadPage;
pub use calendar::CalendarPage;
pub use dashboard::DashboardPage;
pub use forgot_password::ForgotPasswordPage;
pub use guest_details::GuestDetailsPage;
pub use guests::GuestsPage;
pub use hotel_profile::HotelProfilePage;
pub use login::LoginPage;
pub use messages::MessagesPage;
pub use not_found::NotFoundPage;
pub use payments::PaymentsPage;
pub use rates::RatesPage;
pub use reservations::ReservationsPage;
pub use reviews::ReviewsPage;
pub use room_details::RoomDetailsPage;
pub use rooms::RoomsPage;
pub use settings::SettingsPage;
pub use signup::SignupPage;
pub use staff::StaffPage;
